### ISSUE TITLE
Arrumar a responsividade da tela de produto, parece que a imagem está fora view do celular, possibilitando fazer scroll para o lado

### ISSUE THREAD

**Issue by Victoreisdavid** [0spura/hortalink#16]
![Image](https://github.com/user-attachments/assets/d4040a83-3ee1-434d-a74c-3d694d65f654)

**Comment by Victoreisdavid** [comment]
Não consegui reproduzir o problema aqui. Consegue me dizer quais configurações de tela estava usando?

**Comment by 0spura** [comment]
Iphone 12/13 Pro Max 428x926
