### ISSUE TITLE
Terminar a tela do "Meu Perfil"

### ISSUE THREAD

**Issue by Victoreisdavid** [0spura/hortalink#19]

**Comment by Victoreisdavid** [comment]
- A data do backend está vindo errada, impossibilitando a conversão no front.
- A API não retorna o nome do vendedor do produto que o usuário avaliou.

**Comment by Victoreisdavid** [comment]
Adicional: no ratings do vendedor, não retorna o nome do produto avaliado.

**Comment by 0spura** [comment]
Corrigido

![image](https://github.com/user-attachments/assets/81d6c2ad-b37f-4e62-b4ec-84d7f3031622)

**Comment by Victoreisdavid** [comment]
Também não está retornando o nome do vendedor do produto nas avaliações do usuário atual (@me)

**Comment by 0spura** [comment]
Você está falando do meu perfil do vendedor ou do cliente?

![image](https://github.com/user-attachments/assets/2c652945-7b2a-4c7e-be2e-2f4ba47253fa)

No Meu Perfil dos clientes não tem nome do vendedor

![image](https://github.com/user-attachments/assets/3f0e7918-49ca-41dd-8979-7b4ba357e4ed)
