### ISSUE TITLE
Fazer o filtro de usuários na aba de busca

### ISSUE THREAD

**Issue by Victoreisdavid** [0spura/hortalink#20]

**Comment by Victoreisdavid** [comment]
A API só retorna isso:

```json
[{
 "id":3,
 "name":"artur cardoso",
 "avatar":"DA4PDxcXHg8"
}]
```

Mas no protótipo do figma, está com a nota do usuário, suponho que a API deveria retornar isso junto.

**Comment by 0spura** [comment]
Estava pensando, talvez seja melhor deixar a quantidade de seguidores e pedidos recebidos, porque por essa estrela vai fazer a query ficar muito lenta

![Image](https://github.com/user-attachments/assets/979e5f8c-1c10-41e3-a1cc-2ba31ab3bbf9)

**Comment by Victoreisdavid** [comment]
Pode ser isso então. Quando fizer a alteração avisa aqui que eu fecho a issue
