### ISSUE TITLE
403 para POST na api em /v1/sellers/<seller_id>/products

### ISSUE THREAD

**Issue by Victoreisdavid** [0spura/hortalink#21]
### Current Behavior

Quando faço a request para criar um produto `POST /v1/sellers/<seller_id>/products`, ele me retorna 403 sem nenhuma resposta (corpo vazio).

### Expected Behavior

Registrar o produto, ou caso tenha algo errado, retornar uma mensagem de erro dizendo o que está errado.

### Steps To Reproduce

1. Preencha os dados do produto como descrito em `/docs/api.md`.
2. Faça a request post com um FormData

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Other

**Comment by 0spura** [comment]
Apenas usuários com as roles 1 e 4 conseguem acessar essa rota.
